version: 1

project_name: codo

before:
  hooks:
    - go mod tidy
    - go generate ./internal/pack

builds:
  - id: codo
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hergert/codo-agentic-toolkit/cli/cmd.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - builds: [codo]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: hergert
    name: codo-agentic-toolkit
  draft: false
  prerelease: false
