version: 2

project_name: codo

before:
  hooks:
    - go mod tidy

builds:
  - id: codo
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hergert/codo-agentic-toolkit/cli/cmd.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - builds: [codo]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: hergert
    name: codo-agentic-toolkit
  draft: false
  prerelease: false

homebrew_casks:
  - name: codo
    repository:
      owner: hergert
      name: homebrew-tap
    commit_author:
      name: hergert
      email: you@example.com
    directory: Casks
    homepage: "https://github.com/hergert/codo-agentic-toolkit"
    description: "CLI to manage the Codo Agentic Toolkit."
    install: |
      bin.install "codo"

scoops:
  - name: codo
    repository:
      owner: hergert
      name: scoop-bucket
    homepage: "https://github.com/hergert/codo"
    description: "Modern CLI to manage the Codo Agentic Toolkit."

winget:
  - name: codo
    publisher: "Codo Team"
    package_identifier: hergert.codo
    short_description: "Modern CLI to manage the Codo Agentic Toolkit."
    homepage: "https://github.com/hergert/codo"
    repository:
      owner: hergert
      name: winget-pkgs

