version: 1

project_name: codo

before:
  hooks:
    - go mod tidy

builds:
  - id: codo
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hergert/codo-agentic-toolkit/cli/cmd.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - builds: [codo]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: hergert
    name: codo-agentic-toolkit
  draft: false
  prerelease: false
