name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: cli/go.sum

      - name: Verify build
        working-directory: cli
        run: go build ./...

      - name: Vet & Test (race)
        working-directory: cli
        run: |
          go vet ./...
          go test -race ./...

      - name: GoReleaser snapshot (no publish)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v1'
          args: release --clean --snapshot --skip=publish
          workdir: ./cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codo-snapshot-${{ github.sha }}
          path: |
            cli/dist/**/*
          if-no-files-found: ignore

      - name: Refresh embedded pack
        run: ./scripts/embed-pack.sh

      - name: Package pack for dev build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"
          if [ -d pack ]; then
            zip -r "dotclaude-pack.zip" pack
            shasum -a 256 "dotclaude-pack.zip" > "dotclaude-pack.sha256"
          fi

      - name: Publish edge (dev) build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: edge
          name: Edge build
          prerelease: true
          body: |
            Nightly dev build from main
            - Commit: ${{ github.sha }}
            - Date: ${{ github.event.head_commit.timestamp }}
          files: |
            cli/dist/*.tar.gz
            cli/dist/checksums.txt
            dotclaude-pack.zip
            dotclaude-pack.sha256
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
