name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Semver tag to release (e.g., v1.0.0 for major). Leave blank to auto-increment patch version."
        required: false
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for changelog)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: cli/go.sum

      - name: Determine next version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: version
        run: |
          git config user.name "codo-bot"
          git config user.email "actions@users.noreply.github.com"

          if [ -n "${{ inputs.tag }}" ]; then
            # Use provided tag
            NEW_TAG="${{ inputs.tag }}"
          else
            # Auto-increment patch version
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            echo "Latest tag: $LATEST_TAG"

            # Extract version numbers (strip 'v' prefix)
            VERSION=${LATEST_TAG#v}
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)

            # Increment patch
            PATCH=$((PATCH + 1))
            NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          fi

          echo "New tag: $NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

          # Create and push tag
          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Prepare embedded pack & smoke build
        run: |
          ./scripts/embed-pack.sh
          go -C cli build -o /tmp/codo .

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
          workdir: ./cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package dotclaude pack asset
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"
          if [ ! -d pack ]; then
            echo "pack not found; skipping pack asset" >&2
            exit 0
          fi
          zip -r "dotclaude-pack.zip" pack
          shasum -a 256 "dotclaude-pack.zip" > "dotclaude-pack.sha256"

      - name: Upload pack asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dotclaude-pack.zip
            dotclaude-pack.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
